credentials:
  bot_token_key: ODEyXXXXXXXXXXXXXXXXXXXX.XXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXX
  riot_api_key: RGAPI-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
  mongodb_cluster: mongodb+srv://XXXXX:XXXXXX@XXXXXXXX.XXXXX.XXXXXXX.XXX/XXXXXXXX?XXXXXXXXXXX=XXXX&X=XXXXXXXX
