locale: {
  na1: {
    queues: https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/queues.json,
    maps: https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/maps.json,

    tracker_failed: Couldn't start Live-game tracker. Invaild Riot API key.,
    tracker_started: Live-game tracker was started.,
    tracker_stopped: Live-game tracker was stopped.,
    tracker_started_already: Live-game tracker is already working.,
    tracker_stopped_already: Live-game tracker was already stopped.,
    region: Region,
    tracker_list: Live-game tracker Summoner List,
    match_found: New match has been found!,
    loading: Loading data...,

    blue_team: Blue Team,
    red_team: Red Team,
    name: Name,
    tier: Tier,
    ratio: Ratio,
    wins:  Wins,
    losses: Losses,

    invalid_summoner_name: This summoner is not registered. Please check spelling.,
    exists_summoner_name: This summoner was already added in your channel.,
    error: Error occured!,
    db_error: Database Error Occurred.,
    success_added: Summoner have successfully registered.,
    success_removed: Summoner have successfully removed.,
    summoner_not_in_list: Summoner not listed. Enter `!l list` to confirm.,
  },

  kr: {
    queues: https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/ko_kr/v1/queues.json,
    maps: https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/ko_kr/v1/maps.json,

    tracker_failed: 실시간 매치 트래커 시작 실패. Riot API key를 확인해주세요.,
    tracker_started: 실시간 매치 트래커가 시작되었습니다.,
    tracker_stopped: 실시간 매치 트래커가 종료되었습니다.,
    tracker_started_already: 이미 실시간 매치 트래커가 실행중입니다.,
    tracker_stopped_already: 이미 실시간 매치 트래커가 종료되었습니다.,
    region: 지역,
    tracker_list: 실시간 매치 트래커 소환사 목록,
    match_found: 새로운 매치가 발견되었습니다!,
    loading: 데이터 불러오는 중...,
    
    blue_team: 블루 팀,
    red_team: 레드 팀,
    name: 이름,
    tier: 티어,
    ratio: 승률,
    wins:  승,
    losses: 패,

    invalid_summoner_name: 등록되지 않은 소환사입니다. 이름을 확인해주세요.,
    exists_summoner_name: 이미 등록된 소환사입니다.,
    error: 에러 발생!,
    db_error: 데이터베이스 에러 발생.,
    success_added: 소환사가 성공적으로 등록되었습니다.,
    success_removed: 소환사가 성공적으로 삭제되었습니다.,
    summoner_not_in_list: 목록에 없는 소환사입니다. `!l list`를 통해 확인하세요.,
  },
}